import fs from 'node:fs/promises';
import { prisma } from '../src/lib/prisma';

// No-locale path builder
const pathFor = (slug: string) => `/whop/${slug}`;

async function main() {
  console.log('🔨 Building SEO indexes...');
  
  // Prefer Prisma API for portability between dev/prod schemas
  const retired = await prisma.whop.findMany({
    where: { retirement: 'GONE' },
    select: { slug: true },
  });

  const noindex = await prisma.whop.findMany({
    where: { indexingStatus: 'NOINDEX', retirement: 'NONE' },
    select: { slug: true },
  });

  const retiredPaths = retired.map(r => pathFor(r.slug));
  const noindexPaths = noindex.map(r => pathFor(r.slug));

  const code = `// AUTO-GENERATED by scripts/build-seo-indexes.ts
// Do not edit manually
export const RETIRED_PATHS = new Set<string>(${JSON.stringify(retiredPaths, null, 2)});
export const NOINDEX_PATHS = new Set<string>(${JSON.stringify(noindexPaths, null, 2)});
`;

  await fs.mkdir('./src/app/_generated', { recursive: true });
  await fs.writeFile('./src/app/_generated/seo-indexes.ts', code);
  
  console.log(`✅ Generated SEO indexes: retired=${retiredPaths.length}, noindex=${noindexPaths.length}`);
  console.log('📁 Written to: ./src/app/_generated/seo-indexes.ts');
}

main().catch(e => { 
  console.error('❌ Failed to build SEO indexes:', e); 
  process.exit(1); 
});