import fs from 'node:fs/promises';
import { prisma } from '../src/lib/prisma';

const pathFor = (_locale: string, slug: string) => `/whop/${slug}`;

async function main() {
  console.log('🔨 Building SEO indexes...');
  
  // Use raw SQL to avoid enum type issues
  const retired = await prisma.$queryRaw`
    SELECT locale, slug 
    FROM "Whop" 
    WHERE retirement = 'GONE'
  ` as Array<{ locale: string; slug: string }>;

  const noindex = await prisma.$queryRaw`
    SELECT locale, slug 
    FROM "Whop" 
    WHERE "indexingStatus" = 'NOINDEX' AND retirement = 'NONE'
  ` as Array<{ locale: string; slug: string }>;

  const retiredPaths = retired.map(r => pathFor(r.locale, r.slug));
  const noindexPaths = noindex.map(r => pathFor(r.locale, r.slug));

  const code = `// AUTO-GENERATED by scripts/build-seo-indexes.ts
// Do not edit manually
export const RETIRED_PATHS = new Set<string>(${JSON.stringify(retiredPaths, null, 2)});
export const NOINDEX_PATHS = new Set<string>(${JSON.stringify(noindexPaths, null, 2)});
`;

  await fs.mkdir('./src/app/_generated', { recursive: true });
  await fs.writeFile('./src/app/_generated/seo-indexes.ts', code);
  
  console.log(`✅ Generated SEO indexes: retired=${retiredPaths.length}, noindex=${noindexPaths.length}`);
  console.log('📁 Written to: ./src/app/_generated/seo-indexes.ts');
}

main().catch(e => { 
  console.error('❌ Failed to build SEO indexes:', e); 
  process.exit(1); 
});